# Generated by Django 3.1.1 on 2020-12-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PATIENTDETAILS',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=125)),
                ('last_name', models.CharField(default='', max_length=125)),
                ('full_name', models.CharField(default='', max_length=250)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.IntegerField(default=0)),
                ('Age', models.IntegerField(default=0)),
                ('Sex', models.CharField(default='', max_length=6)),
                ('Address_line1', models.CharField(default='', max_length=255)),
                ('Address_line2', models.CharField(default='', max_length=255)),
                ('City', models.CharField(default='', max_length=255)),
                ('State', models.CharField(default='', max_length=255)),
                ('Country', models.CharField(default='', max_length=255)),
                ('Postal_Code', models.CharField(default='', max_length=6)),
                ('Disease', models.CharField(default='', max_length=255)),
                ('Prescription', models.CharField(default='', max_length=500)),
                ('Prescription_date', models.DateField()),
            ],
        ),
    ]
