# Generated by Django 3.1.1 on 2020-12-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_patientdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='Age',
            field=models.CharField(default='', max_length=10),
        ),
    ]
