# Generated by Django 3.1.1 on 2020-12-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_auto_20201212_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='phone',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
