# Generated by Django 3.1.1 on 2020-12-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_auto_20201212_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Address_line1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Address_line2',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Disease',
            new_name='disease',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Postal_Code',
            new_name='postal_Code',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Prescription',
            new_name='prescription',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Prescription_date',
            new_name='prescription_date',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Sex',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='State',
            new_name='state',
        ),
    ]
